declare @Aerolineas table 
( ID_AEROLINEA INT,
NOMBRE_AEROLINEA VARCHAR(200)
)

INSERT INTO @Aerolineas VALUES 
(1, 'VOLARIS'),
(2, 'AEROMAR'),
(3, 'INTERJET'),
(4, 'AEROMEXICO')

--SELECT * FROM @Aerolineas

declare @Aeropuertos table 
( ID_AEROPUERTO INT,
NOMBRE_AEROPUERTO VARCHAR(200)
)

INSERT INTO @Aeropuertos VALUES 
(1, 'BENITO JUAREZ'),
(2, 'GUANAJUATO'),
(3, 'LA PAZ'),
(4, 'OAXACA')

--SELECT * FROM @Aeropuertos

declare @Movimientos table 
( ID_MOVIMIENTO INT,
DESCRIPCION VARCHAR(200)
)

INSERT INTO @Movimientos VALUES 
(1, 'SALIDA'),
(2, 'LLEGADA')

--SELECT * FROM @Movimientos

declare @Vuelos table 
(  ID_AEROLINEA INT,
ID_AEROPUERTO INT,
ID_MOVIMIENTO INT,
DIA DATETIME
)

INSERT INTO @Vuelos VALUES 
(1,1,1,'2021/05/02'),
(2,1,1,'2021/05/02'),
(3,2,2,'2021/05/02'),
(4,3,2,'2021/05/02'),
(1,3,2,'2021/05/02'),
(2,1,1,'2021/05/02'),
(2,3,1,'2021/05/04'),
(3,4,1,'2021/05/04'),
(3,4,1,'2021/05/04')

--SELECT B.NOMBRE_AEROLINEA, C.NOMBRE_AEROPUERTO, D.DESCRIPCION,A.DIA FROM @Vuelos A
--INNER JOIN @Aerolineas B ON A.ID_AEROLINEA = B.ID_AEROLINEA
--INNER JOIN @Aeropuertos C ON A.ID_AEROPUERTO = C.ID_AEROPUERTO
--INNER JOIN @Movimientos D ON A.ID_MOVIMIENTO = D.ID_MOVIMIENTO


SELECT C.NOMBRE_AEROPUERTO, COUNT(DIA) AS VUELOS FROM @Vuelos A
INNER JOIN @Aerolineas B ON A.ID_AEROLINEA = B.ID_AEROLINEA
INNER JOIN @Aeropuertos C ON A.ID_AEROPUERTO = C.ID_AEROPUERTO
INNER JOIN @Movimientos D ON A.ID_MOVIMIENTO = D.ID_MOVIMIENTO
GROUP BY C.NOMBRE_AEROPUERTO
ORDER BY VUELOS DESC

SELECT B.NOMBRE_AEROLINEA, COUNT(DIA) AS VUELOS FROM @Vuelos A
INNER JOIN @Aerolineas B ON A.ID_AEROLINEA = B.ID_AEROLINEA
INNER JOIN @Aeropuertos C ON A.ID_AEROPUERTO = C.ID_AEROPUERTO
INNER JOIN @Movimientos D ON A.ID_MOVIMIENTO = D.ID_MOVIMIENTO
GROUP BY B.NOMBRE_AEROLINEA
ORDER BY VUELOS DESC

SELECT  COUNT(DIA) VUELOS, DIA AS DIA FROM @Vuelos A
INNER JOIN @Aerolineas B ON A.ID_AEROLINEA = B.ID_AEROLINEA
INNER JOIN @Aeropuertos C ON A.ID_AEROPUERTO = C.ID_AEROPUERTO
INNER JOIN @Movimientos D ON A.ID_MOVIMIENTO = D.ID_MOVIMIENTO
GROUP BY DIA
ORDER BY VUELOS DESC

SELECT B.NOMBRE_AEROLINEA, COUNT(DIA) AS VUELOS FROM @Vuelos A
INNER JOIN @Aerolineas B ON A.ID_AEROLINEA = B.ID_AEROLINEA
INNER JOIN @Aeropuertos C ON A.ID_AEROPUERTO = C.ID_AEROPUERTO
INNER JOIN @Movimientos D ON A.ID_MOVIMIENTO = D.ID_MOVIMIENTO
GROUP BY B.NOMBRE_AEROLINEA 
HAVING COUNT(DIA) > 2